#!/usr/bin/env python

import os, sys
# NO_INSTALL{{{
# Coding: Both python2.7 and python3 should execute this code correctly
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),'lib'))
# NO_INSTALL}}}
import fruit.ftoml # Die if there is no TOML
from   fruit import *
MYPY = False
if MYPY:
    from typing import Tuple, Union, Dict
    from fruit.types import AreaValue

def error(msg): # type: (Union[Exception,str]) -> None
    sys.stderr.write("Err: %s\n" % (msg,))
    sys.exit(1)

ARGS = list(sys.argv[1:])

def enhance(to_encode): # type: (Dict[str, AreaValue]) -> Dict[str, AreaValue] # {{{
    if len(ARGS) and ARGS[0][0] == '{':
        to_encode2 = load(ARGS.pop(0).encode('utf8'))
        for k, v in to_encode2.items():
            if ( k not in to_encode or
                 not hasattr(to_encode[k], 'keys') or
                 not hasattr(v, 'keys') ):
                to_encode[k] = v
            else:
                to_encode[k].update(v) # type: ignore
    return to_encode
# }}}

def process_data(data_in): # type: (bytes) -> Tuple[bytes, bool] # {{{
    firstbyte = bytearray(data_in[0:1])
    if len(firstbyte) == 0:
        error("empty input")
    if firstbyte[0] == 1:
        try:
            decoded = decode(data_in)
        except DecoderError as e:
            error(e)
        data_out = dump(decoded)
        is_binary = False
    else:
        try:
            to_encode = load(data_in)
            to_encode = enhance(to_encode)
        except Exception as e:
            error(e)
        try:
            data_out = encode(to_encode)
        except EncoderError as e:
            error(e)
        is_binary = True
    return data_out, is_binary
# }}}

def read_input(): # type: () -> bytes # {{{
    if len(ARGS):
        with open(ARGS.pop(0), "rb") as f:
            data_in = f.read()
    else:
        try:
            data_in = sys.stdin.buffer.read()
        except AttributeError:
            if MYPY:
                data_in = b''
            else:
                data_in = sys.stdin.read()
    return data_in
# }}}

def write_output(data_out, is_binary): # type: (bytes, bool) -> None # {{{
    if len(ARGS):
        with open(ARGS.pop(0), "wb") as f:
            f.write(data_out)
    elif is_binary and sys.stdout.isatty():
        error("Stdout is terminal, refusing to print binary file")
    else:
        try:
            sys.stdout.buffer.write(data_out)
        except AttributeError:
            if not MYPY:
                sys.stdout.write(data_out)
# }}}

data_in = read_input()
data_out, is_binary = process_data(data_in)
write_output(data_out, is_binary)
